export const GC_USER_ID = 'graphcool-user-id';
export const GC_AUTH_TOKEN = 'graphcool-auth-token';
export const AUTH_TOKEN = 'auth-token';
export const RESET_TOKEN = 'uuid';
export const CONFIRM_EMAIL ='uuid';
export const CREATE_MY_DEVICE ='create-my-device'; 
export const CREATE_LETTER ='create-letter'; 
export const DEVICE_NAME = 'device-name';
export const DEVICE_ID ='device-id'
export const MEMBER_ID ='member-id';
export const MEMBER_TOKEN = 'member_token';
export const TEAM_ID ='team-id';
export const TEAM_NAME = 'team-name';
export const TEAM_MEMBER= 'team-member';
export const TEAM_MEMBERID= 'team-member-id';
export const CONFIRM_TEAM_MEMBER = 'confirm-team-member';
